### ISSUE TITLE
R-forge & bioconductor packages?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/Require#12]
leaving a note here to follow up on whether `Require` can correctly handle packages from other repositories, namely R-forge (but also BIoconductor).

E.g., development version of `rgdal` (not yet on CRAN) installed using `install.packages("rgdal", repos="http://R-Forge.R-project.org")`.

**Comment by eliotmcintire** [comment]
THis works:
```
Require::Require("rgdal", repos="http://R-Forge.R-project.org")
```
