### ISSUE TITLE
allow use of private repos for R package

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/Require#2]
use `GITHUB_PAT` env var for accessing private github repos to allow installation of packages.

e.g., putting `"PredictiveEcology/privatePkg"` in a SpaDES module's `reqdPkgs` will currently fail with a 404 error or similar. The workaround is to install `privatePkg` locally using `remotes`/`devtools` and specify `"privatePkg"` in the module's metadata.

**Comment by eliotmcintire** [comment]
This is a `SpaDES.core` issue. I believe this works with `GITHUB_PAT` with any `Require` call.

**Comment by achubaty** [comment]
I'm not sure this is resolved.

**Comment by eliotmcintire** [comment]
THis should be resolved in new CRAN release 0.1.4, if you have a GITHUB_PAT in your environment
