### ISSUE TITLE
setLibPath standalone=TRUE not working

### ISSUE THREAD

**Issue by AbernethyR** [PredictiveEcology/Require#40]
HI, 
Im running Require 0.1.0, although had the same issue with 0.0.13.  R 4.1.2

#Project Library Path
Require::setLibPaths(checkPath(file.path(getwd(), "library"),create = TRUE),
                     standAlone = TRUE)

This does not lead to packages being installed or loaded strictly from the project library.  If the package is installed in the 
"C:/Program Files/R/R-4.1.2/library" library, the package loads from there, even when standAlone=TRUE

**Comment by eliotmcintire** [comment]
Thanks for this. Will look into it.

**Comment by achubaty** [comment]
@eliotmcintire i think this is as 'solved' as it can be -- if a user has installed packages in the system library (which requires admin privileges), then it's up to them to ensure they aren't causing package conflicts with our projects.

**Comment by achubaty** [comment]
has this been resolved in v0.1.4?

**Comment by eliotmcintire** [comment]
This should have been resolved in the new version on CRAN. Please reply if there are still problems.
