### ISSUE TITLE
use 'pak' for package dependency resolution and installation?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/Require#45]
@eliotmcintire there are so many nice features in the `pak` package, that I think we can reduce our maintenance burden if we use this under the hood for dependency resolution and installation:

- identification and auto-installation of and system dependencies (!!)
- package dependency resolution
- caching of deps, downloads, etc. (fast!)
- concurrent installation of packages (fast!)
- built-in  Rstudio Package Manager support for Linux package binaries (fast!)
- supports CRAN, Bioconductor and GitHub packages, as well as additional cran-like repos (e.g., r-universe)
- well supported / maintained -- used by R GitHub Actions and is quite robust

I know you want to keep `Require`'s dependencies very lean, and techincally this only Imports 2 base R packages (though it does Suggest a bunch of others): see https://github.com/r-lib/pak/blob/main/DESCRIPTION#L21-L49.

**Comment by eliotmcintire** [comment]
Do we know how it deals with package version specification? e.g., `reproducible (>= 1.2.9.9011)`?

**Comment by eliotmcintire** [comment]
Wondering also about packages removed from CRAN? e.g., `RandomFields`?  The upcoming `Require` enhancements will install the last available on CRAN archive so as not to break "everything".

**Comment by achubaty** [comment]
1. it should deal with versioning fine;
2. for archived packages it won't directly get them, but I've been using the following workaround: add the package to our PE CRAN-like repo (https://PredictiveEcology.r-universe.dev), and making sure this repo is added to the `options(rcepos = ...)`. Several advantages here over trying to get source code from CRAN archives: r-universe auto-builds the binaries for macOS and Windows -- many packages can't be compiled/built on those platforms without the user having pre-installed and correctly configured all system dependencies.  `pak` handles these additonal repos no problem.

**Comment by achubaty** [comment]
I should note that continuing to use archived packages longer term won't be viable -- so it's really just a stop-gap measure right now.

**Comment by eliotmcintire** [comment]
Yes. But it allows us more control over *when* things break.

**Comment by achubaty** [comment]
Yup - it's been useful since April. No reason though that we can't wrap something to get these archived versions.

**Comment by achubaty** [comment]
This has now been implemented and works well for many cases; however, we are keeping the default option `Require.usePak = FALSE` for now.

Users can enable it using `options(Require.usePak = TRUE)`.

Currently, `pak` fails to resolve the following situations:
1. multiple git branches of the same package are specified (e.g., by different modules). `pak` (correctly) cannot resolve which to use. When not using `pak`, `Require()` uses the version specifications to help decide which to use, so bumping the version on the desired branch and the version requirement in the module helps resolve this scenario. Alternatively, intercept the vector of e.g., module packages and manually resolve any conflicts by removing undesired entries prior to passing the vector of packages to `Require()`.
