### ISSUE TITLE
MRAN to be retired July 1, 2023

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/Require#66]
https://blog.revolutionanalytics.com/2023/01/mran-time-machine-retired.html

Will need to remove this from the package or find suitable alternative.

They specifically mention miniCRAN, which is suitable for internal use, but not something we likely want to create, make generally available and maintain. Perhaps the community will coalesce on some alternative.

**Comment by eliotmcintire** [comment]
Pulled into development, closing
