### ISSUE TITLE
Lack of admin access & install from source failure?

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/Require#97]
I've recently helped someone install `SpaDES.core` and I think there may be an issue related to lack of admin access and being able to install packages from source.

Here's an outline of the issue (which I can't reproduce on my machine)
- Windows machine
- the user has no admin access and R is installed in their Documents folder
- (I'm pretty sure) they have Rtools installed
- They were starting from clean project-level library
- they were working from within an RStudio project

```
options(repos = c(CRAN = "https://cloud.r-project.org"))

## decide where you're working
pkgPath <- file.path( "packages", version$platform,
                     paste0(version$major, ".", strsplit(version$minor, "[.]")[[1]][1]))
dir.create(pkgPath, recursive = TRUE)
.libPaths(pkgPath, include.site = FALSE) ## install packages in project library (proj-lib)

if (!"remotes" %in% installed.packages(lib.loc = pkgPath))
  install.packages("remotes")

if (!"Require" %in% installed.packages(lib.loc = pkgPath) ||
    packageVersion("Require", lib.loc = pkgPath) < "0.3.1") {
  remotes::install_github("PredictiveEcology/Require@55ec169e654214d86be62a0e13e9a2157f1aa966",
                          upgrade = FALSE)
}

## use binary linux packages if on Ubuntu
Require::setLinuxBinaryRepo()

## Notes: 
## 1) if you are working from RStudio and have an older version of base packages like `Rcpp`, `rlang` 
## (and others) installed, you may  need to run the following lines (and code above) directly from R
## in order to update these base packages
## 2) Please ensure the appropriate Rtools version is installed (see)

Require::Require(c("PredictiveEcology/SpaDES.project@transition (HEAD)", 
                   "PredictiveEcology/SpaDES.core@master (HEAD)"),
                 require = FALSE, upgrade = FALSE, standAlone = TRUE)
```

The last line failed as `quickPlot` and `reproducible` could not be installed. Before failure we saw the message that the source version fo the packages was more recent than the binary.

We circumvented the issue by installing the probelmatic dependencies with `install.packages` which had no issues and (I'm pretty sure) installed the source versions of the packages.
```
install.packages("quickPlot")
install.packages("reproducible")
Require::Require(c("PredictiveEcology/SpaDES.project@transition (HEAD)", 
                   "PredictiveEcology/SpaDES.core@master (HEAD)"),
                 require = FALSE, upgrade = FALSE, standAlone = TRUE)
```

I'm unsure what the problem is, as I can't reproduce -- I will try to make another windows user account (with no admin priviledges) to test.

**Comment by achubaty** [comment]
On windows, you can set an option to prevent checking source versions. From `?options`:

> install.packages.check.source:
>    Used by [install.packages](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/install.packages.html) (and indirectly [update.packages](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/update.packages.html)) on platforms which support binary packages. Possible values "yes" and "no", with unset being equivalent to "yes".

If installing the latest `development` versions, prebuild packages can be installed from our R-universe repo:

```r
options(repos = c("https://predictiveecology.r-universe.dev/", getOption("repos")))
```

**Comment by CeresBarros** [comment]
Apparently the issue was related to
1) Rtools being installed but not well configured
2) R version too old (4.1.3)

However your points are great, thanks @achubaty
